version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - BelfordZ
  - shanejonas
  assignees:
  - BelfordZ
  - shanejonas
  ignore:
  - dependency-name: "@open-rpc/typings"
    versions:
    - ">= 1.1.1.a, < 1.1.2"
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@open-rpc/meta-schema"
    versions:
    - 1.14.1
  - dependency-name: "@json-schema-tools/transpiler"
    versions:
    - 1.7.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: inquirer
    versions:
    - 8.0.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: "@open-rpc/typings"
    versions:
    - 1.11.3
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.7
